### ISSUE TITLE
Deprecated selector in `api-workbench\styles\raml-overlay.less`

### ISSUE THREAD

**Issue by SimeonMarkov** [mulesoft/api-workbench#391] opened 2017-01-17 08:20 UTC
In `api-workbench\styles\raml-overlay.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini]::shadow .placeholder-text` => `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini].editor .placeholder-text`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by ddenisenko** [comment] 2017-01-18 18:28
Duplicate of https://github.com/mulesoft/api-workbench/issues/385

**Closed by ddenisenko** 2017-01-18 18:28 UTC
Labels: duplicate
