### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by jarrodek** [mulesoft/api-workbench#506] opened 2017-08-02 22:53 UTC
[Enter steps to reproduce:]

When closing both side panels.

**Atom**: 1.19.0-beta6 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package 0.8.46

### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of undefined

```
At /Users/pawelpsztyc/.atom/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:2255

TypeError: Cannot read property 'destroy' of undefined
    at AtomEditorElement.dispose (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:2255:21)
    at /packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:49
    at Array.forEach (native)
    at TextField.BasicComponent.dispose (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:24)
    at TextField.dispose (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:2705:34)
    at /packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:49
    at Array.forEach (native)
    at WrapPanel.BasicComponent.dispose (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:24)
    at /packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:49
    at Array.forEach (native)
    at Panel.BasicComponent.dispose (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:24)
    at e.detach (/packages/api-workbench/main.js:13:5064)
    at /packages/api-workbench/main.js:13:2900
    at Array.forEach (native)
    at e.t.detach (/packages/api-workbench/main.js:13:2871)
    at e.detach (/packages/api-workbench/main.js:13:5040)
    at e.detach (/packages/api-workbench/main.js:13:5973)
    at e.destroy (/packages/api-workbench/main.js:3:31652)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:707:66)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:683:18)
    at Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:1703:48)
    at HTMLElement.core:close (/Applications/Atom Beta.app/Contents/Resources/app/src/register-default-commands.js:233:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -3:53 core:paste (input.hidden-input)
     -3:52.6.0 intentions:highlight (input.hidden-input)
  4x -3:52.1.0 editor:move-to-beginning-of-word (input.hidden-input)
     -3:51.1.0 intentions:highlight (input.hidden-input)
     -3:51 editor:move-to-beginning-of-word (input.hidden-input)
  5x -3:50.4.0 core:select-right (input.hidden-input)
     -3:48.6.0 intentions:highlight (input.hidden-input)
  6x -3:48.4.0 editor:move-to-end-of-word (input.hidden-input)
     -3:47.1.0 core:move-right (input.hidden-input)
  4x -3:46.9.0 editor:select-to-end-of-word (input.hidden-input)
  3x -3:46 core:select-right (input.hidden-input)
     -3:45.4.0 core:select-left (input.hidden-input)
     -3:44.2.0 core:save (input.hidden-input)
     -3:12.5.0 core:copy (input.hidden-input)
     -2:53.1.0 core:confirm (input.hidden-input)
  2x -0:05.9.0 core:close (div.scrollpad.pane-item.padded.raml-outline)
```

### Non-Core Packages

```
api-workbench 0.8.46 
atom-beautify 0.30.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-jscs 4.1.2 
linter-jshint 3.1.5 
linter-ui-default 1.6.3 
polymer-ide 0.3.0 
polymer-snippets 3.2.1 
```

**Comment by msiladin** [comment] 2017-08-16 14:54
Is there a fix or workaround for this?

**Comment by dreamflyer** [comment] 2017-08-17 01:52
duplicate of #509.

**Closed by dreamflyer** 2017-08-17 01:52 UTC
Labels: bug, priority:high

**Comment by ddenisenko** [comment] 2017-08-17 02:23
@msiladin

>Is there a fix or workaround for this?

We had a hope that 1.19.1 is going to fix it, but it didn't happen. Now, there is a fix from our side incoming, it will be published in several days. As a temporary workaround, close Details pane manually and keep it closed.
