### ISSUE TITLE
Editing becomes very slow as time goes

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#2] opened 2015-11-03 09:48 UTC
It happened recently. Either completion or validation slows things down.

As a reproduction, try typing the following text:

``` RAML
#%RAML 1.0
title: Pet shop
version: 1
baseUri: /shop
types:
  Pet:
    properties:
      name: string
      kind: string
      price: number
    example:
      name: "Snoopy"
      kind: "Mammal"
      price: 100

resourceTypes:

  Collection:
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>[]
    post:
      body:
        application/json:
          type: <<item>>

  Member:
    put:
      body:
        application/json:
          type: <<item>>
    delete:
      responses:
        204:

traits:
  FilterableByPrice:
    queryParameters:
      priceLessThen?:
        type: number
      priceMoreThen?:
        type: number

/pets:
  type: { Collection: {item: Pet} }
  get:
    is: FilterableByPrice
    queryParameters:
      petKind:
       enum: [bird, mammal]
  /{id}:
    type: { Member: {item : Pet} }
```

**Comment by ddenisenko** [comment] 2015-11-03 09:50
Relevant comments:

Pavel: Sorry . It did not looks reproducible for me. I will try to ask for reproduction sequence

Denis: More recommendations. Clone this file 20 times, and try editing the samples one by one. Restarting Atom makes it fast again.

Pavel: okey, so this is a slow down after some time of editing.

Pavel: What we need to do now is to reproduce it again.

**Comment by menduz** [comment] 2016-01-05 13:19
Same here, with a small file using 0.8 spec. Takes about 1sec since I hit a key until its shown on the screen. Maybe the whole file is re-parsed on every change.. In that case a debounce may be good

**Comment by redndahead** [comment] 2016-01-13 06:07
I'll add my voice to this. It gets pretty slow after a while. I'm not sure I can put a finger on the exact cause, but I definitely notice it within the autocomplete.

**Comment by sichvoge** [comment] 2016-01-13 11:44
We are trying to find the root cause, but so far without luck as it appears to be very infrequent and there is no - this is an example to reproduce - case unfortunately.

**Comment by davidpelaez** [comment] 2016-01-20 21:21
I wanted to confirm that this is real. I have removed the package because at some points Atom stops receiving keystrokes and it can't be used. Maybe there's an N+1 loop somewhere or maybe a part of the calculation on the syntax tree can be cached? I'm happy to contribute information like logs or something that could be useful to debug but I don't know what exactly. If you point me in the right direction I can send the data you request.

**Comment by ddenisenko** [comment] 2016-01-20 21:54
@davidpelaez The most hard part here is the issue reproduction. Can you zip and share the RAML project you are encountering this issue at, and described a bit of what you were generally doing when you noticed the issue?

Note: restarting Atom should help.

**Comment by davidpelaez** [comment] 2016-01-21 15:55
I was working on this https://github.com/davidpelaez/erp-api-rjc Basically writing docs, and creating resources and types where autocompletion would appear. Autocompletion seems to play a big deal but this was happening everywhere I typed and I started noticing it progressively emerge as the document got longer.

**Comment by davidpelaez** [comment] 2016-01-21 15:55
Restarting helps but for a very limited time. Let me know if there's anything else I can add to help.

**Comment by davidpelaez** [comment] 2016-01-21 22:03
Also, it was so painfully slow that I just placed a lot of stuff in comments because I needed to send the spec to a customer and I felt bad not having datatypes in 0.8 :P

**Comment by ddenisenko** [comment] 2016-01-26 21:47
@davidpelaez thank you, we reproduced the issue. 

It is hard to fix as it is related to atom's internal code storing links for detached dom nodes, for now you can just close RAML Editor tools (two panels in the right), this should stop leaks to happen.

**Comment by davidpelaez** [comment] 2016-01-26 23:35
It does indeed makes it easier, but I since autocomplete still works in the background the problem persists to some extent. Even with the panels closed it can stop being usable after some minutes of typing.

**Comment by ddenisenko** [comment] 2016-01-26 23:38
@davidpelaez Please confirm if you can reproduce the same issue with:
1) Atom restarted
2) Right after Atom restart Editor Tools are closed and never opened again.

For now I see the memory leak coming from outline details due to detached DOM nodes still live as being referenced from atom's document pollers.

**Comment by ProLoser** [comment] 2016-01-27 01:02
I am curious if this can also be caused by large json files (for examples and schemas) which are then validated against each other, creating recursive parsing and validation. If you make corrections to file paths this also seems to move slowly.

**Comment by rocketraman** [comment] 2016-04-24 20:56
> Please confirm if you can reproduce the same issue with:
> 1) Atom restarted
> 2) Right after Atom restart Editor Tools are closed and never opened again.

I can definitely reproduce the issue with the above two constraints. Let me know what additional information I can provide.

**Comment by ddenisenko** [comment] 2016-04-27 01:53
@rocketraman Please also make sure you do not have API Console opened. So, Atom restart, Editor Tools closed, Console closed, and never opened.

Also, do you see the performance degrading after some time or it is slow from the start?

**Comment by redndahead** [comment] 2016-04-27 15:06
@ddenisenko How do you start it closed. No matter if I close it before exiting atom it always starts with it being opened.

**Comment by sichvoge** [comment] 2016-04-27 15:10
Really, for me the console is never open. I just close the tab where the console is and thats it.

**Comment by redndahead** [comment] 2016-04-27 16:13
Right but what happens when you quit atom and start it again? For me the console and details tabs open again.

**Comment by rocketraman** [comment] 2016-04-27 16:19
> @rocketraman Please also make sure you do not have API Console opened. So, Atom restart, Editor Tools closed, Console closed, and never opened.

Yes, I restart Atom and immediately close the two Editor Tools ("Outline" and "Details") on the right (yes, they reopen on every restart but I don't think there is any way to prevent that -- I just close them right away). The "Issues" list at the bottom is still open... is that what you mean by "Console"? If so, how do I close it?

> Also, do you see the performance degrading after some time or it is slow from the start?

The performance is pretty slow right from the start, but I'm pretty sure it degrades even more over time.

**Comment by rocketraman** [comment] 2016-04-27 17:09
BTW, this might be a useful tool to get a little bit more useful data about this issue: https://pavelfatin.com/typometer/

**Comment by sichvoge** [comment] 2016-04-30 10:14
It also seems that it is not only the API Workbench, but also Atom itself that has problems with performance (see [here](https://discuss.atom.io/t/why-is-atom-so-slow/11376)). We definitely do not stop to analyze the problem here, but its not that easy if the problem does not only is on this package. :(

**Comment by sichvoge** [comment] 2016-05-02 12:45
OK, I've also done some testing. For me editing else becomes slow after some time especially when the Editor Tools are open (Outline and Details). Closing the helps to get better performance. @ddenisenko do you think we can switch to not show them immediately when you open a RAML file?

**Comment by usarid** [comment] 2016-05-02 13:47
Why would we do that, when there could be a problem in our code? See eg https://discuss.atom.io/t/why-is-atom-so-slow/11376/133 . There's a lot of value in these modules, and people might not discover them otherwise. Should we just try harder to understand and maybe work around the problem that's causing slowness in our specific case?


    _____________________________

**Comment by redndahead** [comment] 2016-05-03 23:58
In my opinion if I set the windows to close it should stay closed until I decide to open it again. You should have it opened when atom is first installed, but after that it should be up to me if I ever want to see them again.

And you should fix the actual issue. ;)

**Comment by usarid** [comment] 2016-05-04 00:07
Yes, and yes.

**Comment by sichvoge** [comment] 2016-05-13 12:06
It seems that the details/outline panel might be one problem. We did some more investigation and it seems we have three different tasks to do to see if that will increase the performance. 

1) there are leaks inside the parser and workbench that needs to be fixed
2) optimize the JS parser
3) validation does currently not fully leverage workers in the api workbench

Our current plan is to work us through 1 --> 3, having 1 done with our Monday release.

**Comment by mbonaci** [comment] 2016-11-01 23:57
Yeah, this is a deal breaker (Esp. when I noticed that it has `priority:critical` since March without any feedback). 
I have only 10 small types in my raml file and it got unusable fairly quickly.  
Using the workbench without the navigation panel is like working in text editor, which is, as I'm sure you're aware, a rather tiresome endeavor.

BTW nice work (initially) :)

**Comment by ddenisenko** [comment] 2016-11-02 07:33
@mbonaci Do you have this effect of slowing down as you edit on the latest version of API Workbench? If so, could you please provide RAML example and reproduction sequence?

The leak part is supposed to be fixed, the ticket is still open due to the other slowdowns caused by the general parser performance.

**Comment by sichvoge** [comment] 2016-11-17 12:32
OK. My workbench crashed today after it got really slow. After I started it again it was ok. Attached my RAML document (had to use txt, raml is not supported). I will add details if it slows down again.

[raml-converted.txt](https://github.com/mulesoft/api-workbench/files/597321/raml-converted.txt)

**Comment by ddenisenko** [comment] 2016-12-01 04:06
There are the following aspects, which can be improved:
1. Memory handling
2. Parsing speed
3. Moving parsing activities to background.

Memory handling basically means we need to fix recently discovered memory leaks.
Memory leaks are found in two areas: typesystem and atom edit components.
The first kind of leaks was fixed and will be released soon. This should reduce memory consumption speed greatly and make it quite easier for the users.
The second kind of leaks is under the fixing process right now. I'll provide the updates.

Parsing speed is more related to https://github.com/raml-org/raml-js-parser-2 repository, but, generally, there are two kinds of efforts there: to improve parsing speed in general, and to reuse the results of parsing for the dependent files: fragments, libraries, schemas. The idea is to make improvements for the case when user is continuously modifying a single file so that we try to avoid reparsing other files and reusing previous parsing results instead. This is also something under development right now.

The last efforts is to make all parsing-related activities to run in background so the speed of typing  is unaffected even if those activities consume noticeable amount of CPU. We will start implementing this in about 2 weeks.

**Comment by dreamflyer** [comment] 2016-12-09 06:43
will be published in v0.8.41

**Comment by sonicdivx** [comment] 2017-02-08 16:27
I am seeing this issue, and have the latest version available via "check for updates" within Atom.

**Comment by ddenisenko** [comment] 2017-02-11 03:11
@sonicdivx do you have it "just being slow", or its slows down over time? It easy to check: if restarting Atom makes it fast again for some time, then it's probably the memory leak issue.

**Comment by sonicdivx** [comment] 2017-02-11 17:20
Yes a restart she's improve things and yes eventually slows down. Also I have one include and 10 libraries. Though this did this just temporarily so could minimize scrolling.   If there was a way to turn off validation could narrow down if that is where the leak is occurring

**Comment by ddenisenko** [comment] 2017-02-11 20:12
No, you can't turn off validation, because parsing is something every other component rely upon.

What you can do, for now, is to close RAML editing tools (two panes on the right) and see if it helps. Let us know the results.

We will try reproducing locally. It would be helpful if you can provide RAML (including libraries etc) for reproduction.

**Comment by ddenisenko** [comment] 2017-02-11 20:13
@dreamflyer please try reproducing.

**Comment by sonicdivx** [comment] 2017-02-13 14:23
I may not be able to provide RAML as the API is not publicly available, yet.  I will try closing the other panes and see what happens. I am under a deadline, but if I can anonymize the api I will and send it.

I can tell you that the number of DataTypes is in the hundreds. Endpoints is also very in the hundreds. I did pull the Datatypes into some 20 libraries (not necessarily permanent, just to reduce scrolling).  The Initial version of the API was pulled from .Net using the RAML .Net Tools to autogenerate.  

the reason not using as is, There are some aspects of the definition that are incomplete or DataTypes poorly named (though as I am learning things, I have poorly named a few things - a refactor in my future ;)  )

**Comment by ddenisenko** [comment] 2017-02-14 12:18
We couldn't reproduce the old case that we had. So we really need RAML example to reproduce.

**Comment by wbkoetsier** [comment] 2017-04-10 15:19
Like sonicdivx our RAML file is not publicly available. But it contains some 1900 lines, >200 data types and I think >100 endpoints. There's a lot of inheritance between the types.

Typing has become so slow that I can't use this editor anymore. When I type just a few characters, it will take seconds before they appear on the screen. When I keep typing, for example a long sentence, it might take up to 30 seconds or more before appearing.

The completion function is very slow as well. It takes seconds for the context menu to appear. Once it has, selecting a word is as fast as it is supposed to be. But once selected it takes time to appear.

Validation is very slow as well. Sometimes it hangs, an error for a corrected mistake will not go away until a restart.

Menus and search functionality (ctrl-F) do not slow down, neither does scrolling or navigation to a type or endpoint using the editor tools.

Restarting Atom doesn't help, neither does closing the editor tools or console or any split window or any other open file at startup (or later on).

Based on the above I would say it's related to the validation.

I'm running Atom 1.15.0 x64, API-Workbench 0.8.44 (and linter 2.1.2 with linter-ui-default 1.2.2, intentions 1.1.2 and busy-signal 1.3.0) on Windows 10 (x64, Intel i7, more than enough RAM).

If there really is no other way, I might be persuaded to share (not publicly of course) our RAML file for the purpose of solving this issue. @sonicdivx did you make your deadline and are you able to share an anonymised version of your file like you said? That would very much be my preference, since our API will not become open source for a long time to come (if ever). Incompleteness or poor naming should not affect solving this issue, I'd say don't worry about it.

#164 seems related?

**Comment by ddenisenko** [comment] 2017-04-10 15:33
>Based on the above I would say it's related to the validation.

This is correct. Parsing is slow for big APIs, and anything related to parsing (not only validation) is slowed down. We will soon make available a prototype of API Workbench client for RAML Server. It's a fork of API Workbench, which uses RAML Server for validation, completion, and most other features. This prototype does not have parsing being faster, but it has parsing being performed in the background, so it does not slow down user typing.

**Comment by sonicdivx** [comment] 2017-04-10 17:45
That sounds great. Where should we be looking for this to test it. We are gearing up to have several teams start RAML specs so would like to get an environment setup as soon as possible.

Thanks

**Comment by sichvoge** [comment] 2017-04-10 17:51
@sonicdivx we will publish it into a branch inside this repo, probably with the `wip/` prefix inside the branch name. I will update everyone with another issue with names and how to give feedback.

**Comment by wbkoetsier** [comment] 2017-04-11 06:39
Thank you!

**Closed** 2017-09-27 21:57 UTC
Labels: atom, bug, waiting-for-response
