### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getExtendedType' of null

### ISSUE THREAD

**Issue by yojm** [mulesoft/api-workbench#257] opened 2016-06-30 17:13 UTC
[Enter steps to reproduce below:]

1: Just open a raml file with Atom witn the API-WORKBENCH plugin.

api-workbench: 0.8.33
linter: 1.11.14
linter-raml-myrules: 0.0.6

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.33

### Stack Trace

Uncaught TypeError: Cannot read property 'getExtendedType' of null

```
At /home/user/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/dist/definitionSystem.js:265

TypeError: Cannot read property 'getExtendedType' of null
    at /home/user/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/dist/definitionSystem.js:265:51
    at Array.forEach (native)
    at Universe.register (/home/user/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/dist/definitionSystem.js:262:27)
    at /home/user/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/dist/tsStruct2Def.js:351:15
    at Array.forEach (native)
    at registerClasses (/home/user/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/dist/tsStruct2Def.js:309:17)
    at /home/user/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/dist/tsStruct2Def.js:481:9
    at Array.forEach (native)
    at Object.toDefSystem (/home/user/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/dist/tsStruct2Def.js:480:20)
    at Object.exports.getUniverse.x [as universeProvider] (/home/user/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/dist/definitionSystem.js:976:31)
    at getDefinitionSystemType (/home/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1580:82)
    at Object.fromUnit (/home/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1619:17)
    at CompilationUnit.highLevel (/home/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/jsyaml/jsyaml2lowLevel.js:63:24)
    at Object.s [as ast] (/home/user/.atom/packages/api-workbench/main.js:3:29844)
    at u (/home/user/.atom/packages/api-workbench/main.js:2:4658)
    at l (/home/user/.atom/packages/api-workbench/main.js:2:4422)
    at y (/home/user/.atom/packages/api-workbench/main.js:2:5851)
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:307:9)
    at Object.s [as initEditorObservers] (/home/user/.atom/packages/api-workbench/main.js:2:4144)
    at Object._ [as consumeLinter] (/home/user/.atom/packages/api-workbench/main.js:1:1187)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-raml"
    ]
  },
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
linter, v1.11.14
linter-raml-myrules, v0.0.6

# Dev
No dev packages
```

**Comment by joseluisillana** [comment] 2016-07-01 08:11
Please fix that, I have the same problem

**Comment by ddenisenko** [comment] 2016-09-20 04:47
Fixed.

**Comment by yojm** [comment] 2016-09-22 10:06
Have it been launched in the 0.8.37 version? 

Cause it stills happing. With the api-workbench 0.8.37 and the linter-raml-myrules 0.0.6.

**Comment by joseluisillana** [comment] 2016-09-22 10:23
It doesn't work for me:

- Atom 1.10.2
- API Workbench v0.8.37
- Linter 1.11.16
- Linter-raml-myrules 0.0.6

**Comment by ddenisenko** [comment] 2016-09-28 06:52
There were similar symptoms with API Workbench itself, and that was fixed.

The issue with API Workbench and linter-raml-myrules installed at the same time and conflicting is not fixed. I recommend to disable one of the plugins for the moment, that should help.

**Comment by ddenisenko** [comment] 2016-09-28 06:55
There are two tickets, which appeared to report the same conflict, closing this one as a duplicate of https://github.com/mulesoft/api-workbench/issues/256 for the ease of tracking.

**Closed by ddenisenko** 2016-09-28 06:55 UTC
Labels: bug

**Comment by JohnMcAvinue** [comment] 2016-09-28 09:29
Thanks for fixing. Any idea when it will be available?

**Comment by ddenisenko** [comment] 2016-09-28 09:51
If you get this bug due to the conflict with linter-raml-myrules atom plugin, then it is not fixed yet, I recommend disabling either API Workbench or linter-raml-myrules as an immediate solution.

**Comment by velchev** [comment] 2017-01-30 17:16
Is that fix available and how to apply it? Do I need to update package or what for this?  Thanks!

**Comment by ddenisenko** [comment] 2017-02-11 03:09
This ticket is a duplicate of https://github.com/mulesoft/api-workbench/issues/256

There is no 'fix' for this issue, in order to get rid of the error you should uninstall `Linter-raml-myrules` package.

**Comment by ANPGIT** [comment] 2017-03-13 18:17
Getting same issue after removal of linter-raml-myrules

**Comment by ddenisenko** [comment] 2017-03-15 01:49
@ANPGIT could you please list installed packages?
