### ISSUE TITLE
0.8.39 Error: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by VasaK** [mulesoft/api-workbench#336] opened 2016-10-21 17:23 UTC
Find enclosed document with stack trace..
[Atom-1.9.0-APIWorkbenchStacktrace.txt](https://github.com/mulesoft/api-workbench/files/544912/Atom-1.9.0-APIWorkbenchStacktrace.txt)

**Comment by ddenisenko** [comment] 2016-10-24 15:20
Duplicate of https://github.com/mulesoft/api-workbench/issues/335

**Closed by ddenisenko** 2016-10-24 15:20 UTC
Labels: duplicate
