### ISSUE TITLE
Failed to load the api-workbench package

### ISSUE THREAD

**Issue by Herbert8** [mulesoft/api-workbench#24] opened 2015-11-03 14:19 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.1

### Stack Trace

Failed to load the api-workbench package

```
At Cannot find module 'radioactive'

Error: Cannot find module 'radioactive'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Volumes/Doc/SymbolLinked/bahb/.atom/packages/api-workbench-0.8.1/main.js:1:2035)
  at t (/Volumes/Doc/SymbolLinked/bahb/.atom/packages/api-workbench-0.8.1/main.js:1:183)
  at Object.<anonymous> (/Volumes/Doc/SymbolLinked/bahb/.atom/packages/api-workbench-0.8.1/main.js:1:299)
  at t (/Volumes/Doc/SymbolLinked/bahb/.atom/packages/api-workbench-0.8.1/main.js:1:183)
  at /Volumes/Doc/SymbolLinked/bahb/.atom/packages/api-workbench-0.8.1/main.js:1:270
  at Object.<anonymous> (/Volumes/Doc/SymbolLinked/bahb/.atom/packages/api-workbench-0.8.1/main.js:1:275)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/package.js:725:34)
  at /Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/package.js:176:28
  at Package.module.exports.Package.measure (/Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at Package.module.exports.Package.load (/Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/package-manager.js:363:14)
  at Atom.module.exports.Atom.startEditorWindow (/Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/atom.js:622:21)
  at Object.<anonymous> (/Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/static/index.js:79:25)
  at window.onload (file:///Volumes/App/MacApp/Dev/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by sichvoge** [comment] 2015-11-03 14:24
We are working on that - thanks @Herbert8 for raising it :)

**Comment by sichvoge** [comment] 2015-11-03 14:58
Hi @Herbert8, whilst we are investigating - could you please try to manually install the missing dependency by executing `npm install -g radioactive`. Let me know if that works.

**Comment by Herbert8** [comment] 2015-11-03 15:51
Thank you for your reply. I tried manually install "radioactive" by npm, but it still doesn't work.

**Comment by ddenisenko** [comment] 2015-11-03 15:52
Were there any errors printed during `npm install -g radioactive` execution?

**Comment by petrochenko-pavel-a** [comment] 2015-11-03 15:54
another question is content of node modules in the api-workbench package directory `/Volumes/Doc/SymbolLinked/bahb/.atom/packages/api-workbench-0.8.1/node_modules`
does it contains radioactive, if not does `apm install -d` helps

**Comment by Herbert8** [comment] 2015-11-03 15:55
No. Show you the log:

$ npm install -g radioactive
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 5.0.3
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires uid-number@'0.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/uid-number,
npm WARN unmet dependency which is version 0.0.6
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2 || 3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 5.0.3
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-installed/node_modules/readdir-scoped-modules requires graceful-fs@'^4.1.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-installed/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.8
radioactive@1.6.0 /usr/local/lib/node_modules/radioactive

**Comment by aldonline** [comment] 2015-11-03 15:58
Hi @Herbert8 . What version of NPM are you using? ( `npm --version` )

**Comment by ddenisenko** [comment] 2015-11-03 16:08
Pavel noted a potentially very useful recipe above, please let us know how it goes:

Another question is content of node modules in the api-workbench package directory /Volumes/Doc/SymbolLinked/bahb/.atom/packages/api-workbench-0.8.1/node_modules
does it contains radioactive, if not does apm install -d helps

**Comment by Herbert8** [comment] 2015-11-03 16:09
I've installed radioactive local, the error gone. But a new error appear:
Module version mismatch. Expected 44, got 46.
My npm version is 2.14.7

**Comment by ddenisenko** [comment] 2015-11-03 16:09
How did you install it, via apm or npm?

**Comment by petrochenko-pavel-a** [comment] 2015-11-03 16:10
path_watcher?

**Comment by petrochenko-pavel-a** [comment] 2015-11-03 16:10
I may suggest try to remove all local modules and do apm install -d

**Comment by Herbert8** [comment] 2015-11-03 16:13
No. Since some problem with my network, so I can't install the package by apm. I manually download the package and copy it to .atom/package. Then I exec "npm install" in the package folder. The old error disappeared, but "Module version mismatch. Expected 44, got 46." is reported.

**Comment by ddenisenko** [comment] 2015-11-03 16:15
And what was the way of original workbench module installation? apm or manual copy?

**Comment by Herbert8** [comment] 2015-11-03 16:18
Manual copy. Because  apm does not work. Maybe some problem with my network.

**Comment by aldonline** [comment] 2015-11-03 16:33
@Herbert8 why can't you get APM to run? I would look into that first. Otherwise we can keep going in circles here.
Have you been able to use APM to install other packages?

**Comment by Herbert8** [comment] 2015-11-03 16:37
Oh, it work! I reinstall the package online, all be ok.
Thank you very much!!!:)

**Comment by ddenisenko** [comment] 2015-11-03 17:32
Thank you. Closing the ticket as resolved.

**Closed by ddenisenko** 2015-11-03 17:32 UTC
Labels: Atom, bug, priority:critical

**Comment by GabLeRoux** [comment] 2016-04-15 11:57
I've been getting this error too since a few days now and plugin doesn't seem to work anymore. I uninstalled and installed again using `apm install api-workbench`, but I still get the error.

```
uname -a 
Linux zbookarch 4.5.0-1-ARCH #1 SMP PREEMPT Tue Mar 15 09:41:03 CET 2016 x86_64 GNU/Linux
```

### steps to reproduce

Open Atom

**Atom Version**: 1.7.0
**System**: "Arch Linux"
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.24


### Stack Trace

Failed to load the api-workbench package

```
At ENOENT, renderer/api/lib/remote.js not found in /usr/share/atom/resources/atom.asar

Error: ENOENT, renderer/api/lib/remote.js not found in /usr/share/atom/resources/atom.asar
    at notFoundError (ATOM_SHELL_ASAR.js:110:13)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:435:9)
    at compileFileAtPath (/usr/share/atom/resources/app.asar/src/compile-cache.js:69:23)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:207:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/gableroux/.atom/packages/api-workbench/node_modules/atom-ui-lib/dist/fileDialogUtils.js:2:14)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/gableroux/.atom/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:3206:19)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.r.__extends.t.constructor (/home/gableroux/.atom/packages/api-workbench/main.js:2:18695)
    at t (/home/gableroux/.atom/packages/api-workbench/main.js:1:200)
    at Object.<anonymous> (/home/gableroux/.atom/packages/api-workbench/main.js:2:16463)
    at t (/home/gableroux/.atom/packages/api-workbench/main.js:1:200)
    at Object.<anonymous> (/home/gableroux/.atom/packages/api-workbench/main.js:2:8566)
    at t (/home/gableroux/.atom/packages/api-workbench/main.js:1:200)
    at Object.<anonymous> (/home/gableroux/.atom/packages/api-workbench/main.js:1:325)
    at t (/home/gableroux/.atom/packages/api-workbench/main.js:1:200)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "seti-icons",
      "atom-autocomplete-php",
      "environment"
    ],
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.24
auto-detect-indentation, v1.0.0
autoclose-html, v0.23.0
autocomplete-go, v1.0.6
autocomplete-python, v1.7.2
color-picker, v2.1.1
editorconfig, v1.3.0
emmet, v2.4.3
file-icons, v1.7.2
go-config, v1.1.4
go-get, v1.0.3
highlight-selected, v0.11.2
icon-fonts, v2.4.1
javascript-snippets, v1.2.1
language-clips, v0.2.2
language-ini, v1.16.0
language-nginx, v0.6.1
language-salt, v0.4.0
linter, v1.11.4
linter-pep8, v1.2.1
minimap, v4.21.0
monokai-seti, v0.7.0
node-debugger, v1.4.7
open-recent, v5.0.0
pigments, v0.26.0
python-tools, v0.6.7
seti-ui, v0.9.2
ssh-config, v0.10.1
travis-ci-status, v1.0.0

# Dev
No dev packages
```
