### ISSUE TITLE
API workbench is nearly inpossible to use with atom 1.19.0

### ISSUE THREAD

**Issue by steven-r** [mulesoft/api-workbench#510] opened 2017-08-14 19:43 UTC
During testing of the plugin (with a fresh installation of atom), I receive only exceptions and cannot work with API workbench as every keypress/mouseclick create a failure.

* Create RAML project: Data editing is not possible

![image](https://user-images.githubusercontent.com/4533301/29288576-87f5a98a-8139-11e7-9bea-63dd22d8a4c9.png)

* Opening a RAML from the net: Impossible to edit/change anything.

![image](https://user-images.githubusercontent.com/4533301/29288543-6b62fb38-8139-11e7-9371-9942e377caa8.png)

**Comment by ddenisenko** [comment] 2017-08-16 04:12
Thank you. This is a duplicate of https://github.com/mulesoft/api-workbench/issues/505. In short, Atom 1.19.0 has https://github.com/atom/atom/issues/15111 bug, which causes troubles. It looks to be fixed in 1.19.1. 

There are some other/new exceptions in 1.19.1, but those appear much less frequently, we investigate them atm. Please watch for https://github.com/mulesoft/api-workbench/issues/511 and https://github.com/mulesoft/api-workbench/issues/509 .

**Closed by ddenisenko** 2017-08-16 04:12 UTC
Labels: bug, duplicate
