### ISSUE TITLE
Can not redefine property shadowRoot

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#402] opened 2017-02-02 19:49 UTC
Steps:
Open RAML file. 
Close RAML file.

Result: Exception with the wordings "Can not redefine property shadowRoot"

**Comment by dreamflyer** [comment] 2017-02-02 19:55
duplicate of mulesoft/api-workbench#389.

**Closed by dreamflyer** 2017-02-02 19:55 UTC
Labels: bug, priority:high
