### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by qutwala** [mulesoft/api-workbench#99] opened 2016-01-15 09:45 UTC
[Enter steps to reproduce below:]

1. Create at top level `schemas:` element
2. Inside `schemas:` element type `- test: |`

```yaml
#%RAML 1.0
title: API For ISO3166 Module
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: http://api.api.app/{version}/
mediaType: application/vnd.api+json
schemas: 
  - test: |
```

**Atom Version**: 1.4.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.13

### Stack Trace

Uncaught TypeError: Cannot read property 'value' of null

```
At C:\Users\deivi\.atom\packages\api-workbench\main.js:11

TypeError: Cannot read property 'value' of null
    at Object.P [as schema] (C:\Users\deivi\.atom\packages\api-workbench\main.js:11:19481)
    at t.renderBody (C:\Users\deivi\.atom\packages\api-workbench\main.js:22:22947)
    at C:\Users\deivi\.atom\packages\api-workbench\main.js:22:24337
    at Array.map (native)
    at C:\Users\deivi\.atom\packages\api-workbench\main.js:22:24312
    at Array.map (native)
    at t.render (C:\Users\deivi\.atom\packages\api-workbench\main.js:22:24044)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:789:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:816:14)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:237:30)
    at Object.ReactReconciler.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:400:40)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:306:16)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:251:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:470:12)
    at ReactDOMComponent.Mixin.updateComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:319:10)
    at ReactDOMComponent.Mixin.receiveComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:303:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:524:23)
    at Object.ReactReconciler.performUpdateIfNecessary (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:115:22)
    at runBatchedUpdates (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:151:21)
    at ReactReconcileTransaction.Mixin.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.assign.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:95:38)
    at Object.flushBatchedUpdates (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:175:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:207:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:148:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactDefaultBatchingStrategy.js:66:19)
    at Object.enqueueUpdate (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:215:22)
    at enqueueUpdate (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdateQueue.js:30:18)
    at Object.ReactUpdateQueue.enqueueElementInternal (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdateQueue.js:290:5)
    at C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:332:24
    at Object.ReactMount.scrollMonitor (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:312:5)
    at Object.ReactMount._updateRootComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:331:16)
    at Object.ReactMount.render (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:457:27)
    at t.render (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:8210)
    at t.updateRAML (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:9621)
    at t.updateUnit (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:11048)
    at C:\Users\deivi\.atom\packages\api-workbench\main.js:1:5865
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\deivi\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\deivi\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\deivi\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1321:25
```

### Commands

```
     -4:26.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:12.8.0 core:copy (atom-text-editor.editor.is-focused)
     -4:09.3.0 core:paste (atom-text-editor.editor.is-focused)
     -4:06.3.0 core:save (atom-text-editor.editor.is-focused)
     -3:58 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:51.4.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:51.1.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -3:50.1.0 core:undo (atom-text-editor.editor.is-focused)
     -3:47.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:58.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:55.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:53.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:35.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:27.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:27.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.13
linter, v1.11.3

# Dev
No dev packages
```

**Comment by ddenisenko** [comment] 2016-01-15 14:52
Thank you for reporting. I copy-pasted your code, fixed indents and could not reproduce it. Tried re-typing last line, still no luck.

Could you please attach the whole RAML file?

**Comment by qutwala** [comment] 2016-01-16 11:52
That's weird, i can't reproduce it no more too..

**Comment by sichvoge** [comment] 2016-01-18 13:19
Could not re-produce as well. Also opened console and details view that uses these information and could produce that error. No luck! @qutwala shall we close it?

**Comment by qutwala** [comment] 2016-01-18 14:40
Ok, let's close it. If this error appear again i will update with GIF and other helpful information.

**Comment by sichvoge** [comment] 2016-01-18 14:40
Cool! thanks

**Closed by sichvoge** 2016-01-18 14:40 UTC
Labels: atom, bug
