### ISSUE TITLE
Deprecated calls - Atom core : Autocomplete provider

### ISSUE THREAD

**Issue by jy95** [mulesoft/api-workbench#440] opened 2017-03-20 20:06 UTC
### Description

[Description of the issue]

I use https://atom.io/packages/api-workbench and I often see this message

![bugatom](https://cloud.githubusercontent.com/assets/9306961/24093275/55667ea4-0d53-11e7-9c39-3c7bd4ac6ffd.png)

**Expected behavior:** [What you expect to happen]

I expect this issue to be solved by update but it is not the case.

**Actual behavior:** [What actually happens]

Not solved:

```
atom core (1 deprecation)
Autocomplete provider 'Object(undefined)' returns suggestions with a prefix attribute. 
The prefix attribute is now replacementPrefix and is optional. 
See https://github.com/atom/autocomplete-plus/wiki/Provider-API
AutocompleteManager.deprecateForSuggestion - C:\Users\Jacques\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:484:14
<unknown> - C:\Users\Jacques\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:341:38
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Each time that Atom seems to check for update

### Versions
Atom : 1.15.0
Electron: 1.3.13
Chrome : 52.
OS : Windows 10 64 bit Education

### Additional Information

Already posted on Atom github thinking It was a issue from atom : https://github.com/atom/atom/issues/14036. Believe @50Wliu , this error isn't related to Atom

**Comment by dreamflyer** [comment] 2017-03-23 06:32
Can not to reproduce. Looks like duplicate of #415 which is already fixed. Try to install the latest version of API Workbench and recheck the issue.

**Comment by jy95** [comment] 2017-03-23 08:07
I was on v0.8.43 version. v0.8.44 is only out from 3 days XD. I will give it a try

**Closed** 2017-04-13 16:34 UTC
Labels: enhancement, waiting-for-response
