### ISSUE TITLE
api-workbench slows to a crawl after 30 mins of use

### ISSUE THREAD

**Issue by mrose-avenuecode** [mulesoft/api-workbench#127] opened 2016-02-19 05:54 UTC
after I have been using api-workbench for about 30 minutes or so, performance begins to degrade noticeably. before long, it gets to the point where it takes 10 - 15 seconds for the UI to respond again after i relocate the cursor with a mouse click. scrolling vertically also lags significantly as well. after i restart atom, all is well again for another 30 minutes or so.

**Comment by redndahead** [comment] 2016-02-19 17:17
This is probably the same issue that was opened here: https://github.com/mulesoft/api-workbench/issues/2

It's a known issue and they currently believe it's a bug with atom.  There are some suggestions in there.

**Comment by ddenisenko** [comment] 2016-03-08 05:21
Yes, this is a known memory leak issue. It will be fixed at some point, unfortunately it is hard to do. Closing RAML editor tools (those two panels to the right) after Atom restart helps to work it around for now.

**Comment by ddenisenko** [comment] 2016-03-08 05:21
Closing as duplicate of #2

**Closed by ddenisenko** 2016-03-08 05:21 UTC
Labels: duplicate
