### ISSUE TITLE
Error during api-workbench installation on Ubuntu

### ISSUE THREAD

**Issue by eguider** [mulesoft/api-workbench#28] opened 2015-11-04 04:10 UTC
I got the following error when installing workbench:

```
sudo apm install api-workbench
Installing api-workbench to /home/tboukhcha/.atom/packages ✗

> spawn-sync@1.0.14 postinstall /tmp/apm-install-dir-115103-5956-ck4r1p/node_modules/api-workbench/node_modules/spawn-sync
> node postinstall


> runas@3.1.1 install /tmp/apm-install-dir-115103-5956-ck4r1p/node_modules/api-workbench/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild


> oniguruma@5.1.2 install /tmp/apm-install-dir-115103-5956-ck4r1p/node_modules/api-workbench/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
> node-gyp rebuild



module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-115103-5956-ck4r1p/node_modules/api-workbench/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
gyp ERR! configure error 
gyp ERR! stack Error: EACCES, mkdir '/tmp/apm-install-dir-115103-5956-ck4r1p/node_modules/api-workbench/node_modules/pathwatcher/node_modules/runas/build'
gyp ERR! System Linux 3.13.0-66-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115103-5956-ck4r1p/node_modules/api-workbench/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES, mkdir '/tmp/apm-install-dir-115103-5956-ck4r1p/node_modules/api-workbench/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/build'
gyp ERR! System Linux 3.13.0-66-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115103-5956-ck4r1p/node_modules/api-workbench/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/tboukhcha/.atom/.apm/.apmrc" "--userconfig" "/home/tboukhcha/.atom/.apmrc" "install" "/tmp/d-115103-5956-1190l7h/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.14 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.14 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115103-5956-ck4r1p/npm-debug.log
```

**Comment by eguider** [comment] 2015-11-04 04:20
using the Atom packages installer, I got : 
![image](https://cloud.githubusercontent.com/assets/3514896/10929443/73dada8c-8281-11e5-93a8-c9dd72540ac1.png)

**Comment by petrochenko-pavel-a** [comment] 2015-11-04 05:04
Hi @eguider thanks a lot for posting this, we are currently investigating the reasons and will come with a solution as soon as possible (hopefully to the evening). 

It seems to be related to the https://github.com/ForbesLindesay/spawn-sync/issues/11 

after we will have a fix I will probably try to ask you to test if it works for you.

Thanks in advance,
Pavel

**Comment by sichvoge** [comment] 2015-11-04 18:03
@eguider can you try it with version 0.8.5 again please and let us know if that worked for you.

**Comment by eguider** [comment] 2015-11-04 18:41
Hi guys, the installation works fine thanks, but I cant see the "Add new..." and "Reveal in Tree View" menu when I click-right as described in the docs : http://apiworkbench.com/docs/
![image](https://cloud.githubusercontent.com/assets/3514896/10947838/770811c6-82f8-11e5-90f4-bab810b4c622.png)
should I create an issue for this?

the code completion works fine after adding the first line (#%RAML 1.0)

**Comment by petrochenko-pavel-a** [comment] 2015-11-04 18:45
Hi @eguider "Reveal in Tree View" should work after you will toggle tree view to be visible, but the fact that you are not seeing 'Add new' is pretty strange. Do you see 'Add New' category in the detail view when you have something typed?

Thanks in advance,
Pavel

**Comment by ddenisenko** [comment] 2015-11-04 18:48
Please do the following:
1) Type the following text into RAML file:
```RAML
#%RAML 1.0
title: Test
/test:
```
2) Open "Palette" tab in Details pane. Details pane is located in the bottom-right corner of the screen.

See if there are green buttons called "Add new resource", "Add new method" etc.

**Comment by eguider** [comment] 2015-11-04 19:05
@petrochenko-pavel-a it works after clicking on "Open RAML Editor Tools" : 
![image](https://cloud.githubusercontent.com/assets/3514896/10948624/8759a0f4-82fc-11e5-97f8-a4d4b4a10ce7.png)

@ddenisenko It works, thanks.

great work!!

**Comment by petrochenko-pavel-a** [comment] 2015-11-04 19:06
So closing the issue. Thanks @eguider

**Comment by ddenisenko** [comment] 2015-11-04 19:08
@eguider Okay, please check if you are still unable to see "Add new..." in the context menu, that appears on right-click.

So, with the same RAML text as above, set cursor at "/test:", then right-click it and check if you have "Add new..." sub-menu in the context menu.

**Comment by eguider** [comment] 2015-11-04 19:23
@ddenisenko yes all works fine, when I right click on a blank file, I get "Add new...> add new resource + create new API" (even if the add new resource gives a nullity error "Cannot read property 'unit' of null" because there is no RAML header I guess)

the right click on a resource "/test" gives  "Add new...> add new resource + add new method + create URI parameter"

**Comment by ddenisenko** [comment] 2015-11-04 19:28
Sounds good, but initially you did not see "Add new..." in the context menu. What changed? I guess, this item appeared in the context menu after you launched "Open RAML Editor Tools"?

**Comment by eguider** [comment] 2015-11-04 19:34
@ddenisenko yes exactly.

**Comment by ddenisenko** [comment] 2015-11-04 19:36
@eguider Thank you. Any chance to reproduce the initial state (when you do not have RAML Editor Tools opened and thus no items in question visible in context menu)?

**Comment by eguider** [comment] 2015-11-04 19:41
@ddenisenko, I can't reproduce, I tried closing all panels and create a new file, close and reopen Atom, I didn't get the problem anymore.

Thanks

**Comment by ddenisenko** [comment] 2015-11-04 19:45
@eguider Okay, thanks again. Closing the issue for now, lets see if anyone else runs into it.

**Closed by ddenisenko** 2015-11-04 19:45 UTC
Labels: bug, priority:critical

**Comment by itng02** [comment] 2017-06-10 16:30
I'm still unable to see "Add New..." in the context menu. Have tried launching "Open RAML Editor Tools" as well but it doesn't work.

My workbench installation was successful however when I launch Atom, I see below screen all the time on top-right corner of the editor...not sure what dependencies it is trying to install..despite following every single step from the Installation guide https://github.com/mulesoft/api-workbench/wiki/Installation-Tips

![image](https://user-images.githubusercontent.com/29337924/27004517-3f4aaf76-4dd8-11e7-9ec6-2b41fd4357e2.png)
